// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  enemyId: __t.u64().primaryKey().name("enemy_id"),
  entityId: __t.u64().name("entity_id"),
  kind: __t.string(),
  hp: __t.u32(),
  maxHp: __t.u32().name("max_hp"),
  alive: __t.bool(),
  anchorX: __t.f32().name("anchor_x"),
  anchorY: __t.f32().name("anchor_y"),
  anchorZ: __t.f32().name("anchor_z"),
});
