import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
	guide: [
		'intro',
		{ type: 'autogenerated', dirName: 'getting-started' },
		{ type: 'autogenerated', dirName: 'game-and-stages' },
		{ type: 'autogenerated', dirName: 'entities' },
		{ type: 'autogenerated', dirName: 'behaviors' },
		{ type: 'autogenerated', dirName: 'actions' },
		{ type: 'autogenerated', dirName: 'input' },
		{ type: 'autogenerated', dirName: 'camera' },
		{ type: 'autogenerated', dirName: 'rendering' },
		{ type: 'autogenerated', dirName: 'physics' },
		{ type: 'autogenerated', dirName: 'audio' },
		{ type: 'autogenerated', dirName: 'cinematics' },
		{ type: 'autogenerated', dirName: 'assets-and-data' },
		{ type: 'autogenerated', dirName: 'editor-integration' },
	],
	api: [{ type: 'autogenerated', dirName: 'api' }],
	architecture: [{ type: 'autogenerated', dirName: 'architecture' }],
};

export default sidebars;
